@startuml

package "platform" {
    () "CoreBootstrap" as CB
    [CoreApplicationRunner] as CAR

    [BrokerBootstrap] as BB
    [BrokerApplicationRunner] as BAR

    CB --> BB
    CAR --> BAR
}

package "data" {
    () "Data" as d
    d --> [FinnhubData]
}

package "persistence" {
    () "Persistence" as p
    p --> [Postgres]
}

@enduml