@startuml

actor cli

participant CoreBootstrap as CB
participant AlpacaBootstrap as ACB
participant DataService as DS
database PersistenceDAO as PD
participant ComputeService as CS

cli -> CB: boot

CB -> ACB: login()
return UserSession

CB -> ACB: getMargin()
return accountMargin

CB --> ACB: getAllInstruments()
return instrumentList

CB --> ACB: getTradingInstruments()
return filteredInstrumentList

CB --> ACB: initWebSocket()
return true

CB --> ACB: streamTicks()
return true

CB --> ACB: scheduleTicksAggregator()
return true

@enduml